### ISSUE TITLE
Loading time of iframe elements

### ISSUE THREAD

**Issue by JohnONolan** [stripe/elements-examples#21]
Hi team, we're working on an implementation of a form using Stripe Elements and struggling with the really noticeable flash/delay when fields are loaded in via iframe. I've noticed this is also present on the actual examples provided here, and wondered if you have any thoughts about how this could be improved?

Unfortunately it's not possible to load some static HTML and then smoothly replace that when elements are mounted, there's still a big delay where the placeholder disappears, and then the stripe field is later loaded in.

Can't seem to find a way to have this load in a visually pleasing way which isn't overly noticeable. 

![stripe](https://user-images.githubusercontent.com/120485/33113898-55124cf8-cf95-11e7-9e8e-f6c1fd73dd11.gif)

**Comment by jez** [comment]
Hey @JohnONolan! I can confirm that we see the delay on our end as well.

One thing that you should be able to do (which we aren't doing in our examples) is to set a minimum height on the div you mount the element into. That way the page doesn't jump so visibly when it loads.

Other than that, it's one of our current priorities to make Elements load and render faster, so it will get faster over time.

Thanks again for bringing this to our attention!

**Comment by jez** [comment]
Oh, another thing you can do in conjunction with setting a minimum height is render some sort of "loading" or "disabled" overlay on top of the mount wrapper element, and listen to the `ready` event from Elements to remove the overlay.
