### ISSUE TITLE
elements-examples/js/example2.js

### ISSUE THREAD

**Issue by alfasin** [stripe/elements-examples#22]
Where does the function `registerElements()` comes from? there is no import?

**Comment by jez** [comment]
It's good old-fashioned script load order:

https://github.com/stripe/elements-examples/blob/e7b33a0d7ef1d954f73e68f8b173802168fa53e9/index.html#L15

https://github.com/stripe/elements-examples/blob/e7b33a0d7ef1d954f73e68f8b173802168fa53e9/js/index.js#L5

There is no build step in elements-examples, so we can't use `import`s.
