### ISSUE TITLE
Auto Scrolls to Top

### ISSUE THREAD

**Issue by Viggoleinen** [stripe/elements-examples#25]
Hi!

Using an iPhone (X in my case), fill out the first form with name, email, phone and credit card number and click on "Pay $25" (without entering expiry date and cvc) - you will notice the page automatically scrolls to the top.

How can it be fixed? Attached is zip file containing screen recording.

[ScreenRecording.MP4.zip](https://github.com/stripe/elements-examples/files/1535162/ScreenRecording.MP4.zip)

**Comment by remi-stripe** [comment]
@Viggoleinen I'd recommend talking to our support team directly for this instead (which I think you're doing already). Make sure to provide them with enough information for them to reproduce such as the exact browser version, iphone version, etc.
