### ISSUE TITLE
Do You Write the HTML in elements? 

### ISSUE THREAD

**Issue by harrydry2** [stripe/elements-examples#28]
Sorry for the stupid question, but I genuinely unsure. 

Do you write HTML for the element? 
Or is that automatically inserted? 

On the docs it says: 
 

Implying that the "pre-built component" is inserted.

But on the git hub, your showing an index.html with lots of html for the elements?

**Comment by asolove-stripe** [comment]
Hi @harrydry2! There are two different sets of html for a form using elements. For the form itself, including fields like name and phone number that your site controls, you will need to write your own html. In that html, where you want the credit card field to go, you should put an empty node, like a div, with the right size and location on your page for that field. When you create the element via JavaScript, its iframe and all the html needed to render the actual credit card field will be inserted inside your placeholder. 

A good example is [in our html example for this repo](https://github.com/stripe/elements-examples/blob/master/index.html#L102). You can see that above and below the highlighted line is lots of html that the site author has written to build the rest of their form. And where the credit card field should go is an empty `<div>` that the credit card field itself will eventually get inserted into.

Hope that answers your question! If not, let me know how else we can help.

**Comment by harrydry2** [comment]
Great Explanation. Thank You! 

I actually figured this out myself other the weekend and got a checkout working. Got to say, stripe Elements is unbelievably good. Thanks a lot.
 
Although I know the Stripe Docs are legendary, I think a short video series would help. 

After watching this video: https://www.youtube.com/watch?v=BB-nXTPyNtE 

things became obvious very quickly.
