### ISSUE TITLE
On Blur() does not close keyboard

### ISSUE THREAD

**Issue by tsmith123** [stripe/elements-examples#31]
Not sure where to add this issue as there doesn't seem to be a repo for Stripe Elements - just the examples. Please move if somewhere more suitable.

I am using Stripe Elements and testing on my iPhone 7 on Safari and Chrome. Both browsers produce the same results. When I leave (blur) from the Stripe Elements input box by tapping somewhere outside of the control, the keyboard does not close. This causes issues because if I then click the Done button on the top right to close the keyboard, it will re-appear when I tap anywhere on the screen.

Comparing to a standard input box, when I leave, the keyboard closes as expected.

Any recommendations?

**Comment by tsmith123** [comment]
Fixed with a hack. Added a hidden input and set focus to this when leaving Stripe input box, then blur.

**Comment by grahamcracker** [comment]
I'm also experiencing this (iOS 11, Mobile Safari). Not sure what is causing this, but it's definitely an issue with Stripe Elements because it even happens on the demo page: https://stripe.com/docs/stripe-js
