### ISSUE TITLE
Is Country Field is not needed?

### ISSUE THREAD

**Issue by gety9** [stripe/elements-examples#32]
Guys hi,

We are using stripe v2 now, and use country to detect if zip is needed or not.

I was thinking that with stripe components we will need it too and will need to create something like this:
[screenshot](https://puu.sh/yYI9u/4d26fd3e67.png)

But after reading this https://github.com/stripe/elements-examples/issues/11
seems like you detect if zip is needed or not by credit card number?
So country field is not needed.

Did i understand it right?

**Comment by jez-stripe** [comment]
That's correct; we automatically detect whether to prompt for a ZIP or
Postal code in the `card` element.

**Comment by gety9** [comment]
Thank you for your reply!
