### ISSUE TITLE
Is it possible to move error message

### ISSUE THREAD

**Issue by gety9** [stripe/elements-examples#33]
Sorry if it's too basic question,

but is it possible to move error message?

Something like this > https://puu.sh/yYKoH/91a2782dde.png ?

**Comment by jez-stripe** [comment]
Hey @gety9!

The code for rendering the HTML is all here in this repo. You can shuffle
around the page structure however you see fit. For example, this is the
element that error messages render into:

https://github.com/stripe/elements-examples/blob/master/index.html#L111

If you're having trouble with your integration, feel free to reach out to
our support team using https://support.stripe.com/
