### ISSUE TITLE
Do you have samples for using ACH, all of your samples are using credit card?

### ISSUE THREAD

**Issue by iamrommel** [stripe/elements-examples#34]
Do you have samples for using ACH, all of your samples are using credit card?

**Comment by cweiss-stripe** [comment]
Hi @iamrommel 
This repository only contains examples for [Stripe Elements](https://stripe.com/elements), our UI Components library, and there are currently only Elements for credit cards and Payment Request.
Until we add more Elements and corresponding examples, you can refer to our ACH integration guide: https://stripe.com/docs/ach
