### ISSUE TITLE
Enter key within card fields doesn't validate other fields.

### ISSUE THREAD

**Issue by pderksen** [stripe/elements-examples#35]
When you hit Enter within one of the card fields, the validation rules on all the non-card fields is ignored and the form submits. However, validation is triggered properly if the Pay button is clicked instead. Tried this with the first 2 examples.

**Comment by jez** [comment]
Sorry for the accidental close!

Thanks for bringing this to our attention! I can confirm that I'm seeing the behavior you mention.

The issue in particular comes from the fact that we're using the HTML5 `required` attribute for non-Elements fields, while Elements has its own way of checking validation.

We'll need to add some checks to see if any of the non-Elements fields haven't been filled in.

**Comment by pderksen** [comment]
@jenan-stripe @jez Works great for me so far. Thanks!
