### ISSUE TITLE
registerElements function is undefined

### ISSUE THREAD

**Issue by Juli0GT** [stripe/elements-examples#36]
The function registerElements that you include at the end of the example you have on your github repo doesn't exist.

https://github.com/stripe/elements-examples/blob/master/js/example3.js

https://stackoverflow.com/questions/47540838/stripe-registerelement-not-defined

**Comment by jez** [comment]
In fact, it is defined:

https://github.com/stripe/elements-examples/blob/master/js/index.js#L5

Hope this helps!
