### ISSUE TITLE
Not responsive under 370 px

### ISSUE THREAD

**Issue by nexussmart** [stripe/elements-examples#41]
Hello,

We used your form in mobile but there are not responsive under 370px.
In effect for iPhone 5 (320px), Galaxy S5 (360px), Nexus 5 (360px) the span of day/month be over the span of the card number.

Thank's for your help.

<img width="359" alt="capture d ecran 2018-03-06 a 11 54 28" src="https://user-images.githubusercontent.com/30287100/37028750-70b83a70-2135-11e8-92cf-8be181e80e12.png">
<img width="316" alt="capture d ecran 2018-03-06 a 11 54 52" src="https://user-images.githubusercontent.com/30287100/37028751-70d618e2-2135-11e8-9785-6e3270454787.png">

**Comment by jez** [comment]
Thanks for pointing this out! I've opened #43 which should solve this.
