### ISSUE TITLE
Not working on iOS for Hybrid application

### ISSUE THREAD

**Issue by nexussmart** [stripe/elements-examples#42]
Hello,

We want to implement your form on our hybrid application in ionic1 but we have some errors.
For the simply form https://stripe.com/docs/stripe-js/elements/quickstart and others examples https://stripe.github.io/elements-examples/fr/

- automatic switch from one field to another does not work
- on iPhone 6 the form isn't good responsive
- there are problems with the keyboard

On the internet other developers have encountered this type of problem.
It's a shame because there is no other viable 3DS solution to integrate your solution in a hybrid application.

Thank's for your help,

**Comment by jez** [comment]
Hey @nexussmart!

For general help with your integration, you can reach out to our support team at https://support.stripe.com or using #stripe on Freenode.

Since this isn't an issue with elements-examples specifically, I'm going to close this.
