### ISSUE TITLE
css color property not working on completed stripe elements

### ISSUE THREAD

**Issue by pavittarx** [stripe/elements-examples#46]
In the screen snip below, you can see, the color property is not working on stripe elements.
I want the text to appearing green, that indicate the supplied input is valid, it is fine with the elements, I have created but, fails on elements, mounted via stripe.
All the other properties, are working fine, the color is visible in other states, but it fails on 'completed' state.
![image](https://user-images.githubusercontent.com/29155477/38656140-43d398f6-3e36-11e8-8720-45a5107ac64d.png)

My HTML for forms - 
```html
<section`` class="stripe_form_wrapper">
            <form id="stripe-form" class="stripe_form_container" method="post" action="/charge">
              <input id="name" type="text" placeholder="Name" required>
              <div id="card-number">
              </div>
              <div id="card-expiry" class="stripe_break"></div>
              <div id="card-cvc" class="stripe_break"></div>
              <div id="stripe-error"></div>
              <button> Pay </button>
            </form>
          </section>
        </section>
```

Javascript 
```javascript
/* Creates an instance of Stripe Object, on the client browser using Publishable Key */
let stripe = Stripe('-stripe-publishable-key-here-');

/* This method creates an instance of Stripe elements, which manages a group of Elements. */
let elements = stripe.elements();

/* Creates an instance of specific element */

let classes = {
    base: 'stripe_base',
    empty: 'stripe_empty',
    focus: 'stripe_focus',
    invalid: 'stripe_invalid',
    complete: 'stripe_complete'
}

let style = {
    completed: {
        color:'#00e676;'
    }
}
let cardNumber = elements.create('cardNumber', { classes: classes, style:style});
cardNumber.mount('#card-number');

let cardExpiry = elements.create('cardExpiry', { classes: classes });
cardExpiry.mount('#card-expiry');

let cardCvc = elements.create('cardCvc', { classes: classes,});
cardCvc.mount('#card-cvc');


function error(elementInstance) {
    elementInstance.addEventListener('change', function(event) {
        let err = document.getElementById('stripe-error');
        if (event.error) err.innerHTML = event.error.message;
        else err.innerHTML = '';
    })
}

error(cardNumber);
error(cardExpiry);
error(cardCvc);

console.log(cardNumber);
console.log(cardExpiry);
console.log(cardCvc);

var form = document.getElementById('stripe-form');
form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(cardNumber).then(function(result) {
        if (result.error) {
            // Inform the user if there was an error.
            var errorElement = document.getElementById('stripe-errors');
            errorElement.textContent = result.error.message;
        } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
        }
    });
});

function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form to the Server
    form.submit();
}
```

CSS
```

.stripe_form_wrapper{
    background-image: url("/assests/images/cookery.gif");
    padding:0.5rem;
    
}

/* Set Base Styles for Stripe Input elements*/
.stripe_form_container{
    background: #ffffffc0;
    width:70%;
    margin:2rem auto;
    padding:1rem;
    border:0.1rem solid #1976d2;
}

.stripe_form_container input{
    background-color:#ffffff00;
    margin-bottom:0;
}

.stripe_form_container input, .stripe_base {
    width:70%;
    padding:0.3rem;
    margin-bottom:0.7rem;
    box-shadow: 0 0 0.2rem #454545c0;
    transition: 0.2s all linear;
}

.stripe_form_container input:focus,.stripe_focus {
    color: initial;
    box-shadow: 0 0.2rem 0.1rem -0.1rem #1976d2a0;
}

.stripe_form_container input:invalid,.stripe_invalid {
    color:#ff0000;
    box-shadow: 0 0.2rem 0.1rem -0.1rem #ff0000ff;
}

.stripe_form_container input:valid,.stripe_complete{
    color:#00e676;
    box-shadow: 0 0.2rem 0.1rem -0.1rem #00e676;
}

.stripe_form_container input:placeholder-shown, .stripe_empty{
    color:inherit;
    box-shadow: 0 0 0.2rem #454545c0;
}

.stripe_break{
    display: inline-block;
    width:2.7rem;
    margin-right:0.5rem;
}
```

You can see I have tried to supply the color via Javascript style object as well as CSS class, but any of them doesn't work. The result is same as in the image.
Thanks.

**Comment by jez** [comment]
You want to use `complete`, not `completed`.

If you could do me a favor, can you check the console? I believe you should see an error that warns that `completed` is not a recognized property. If that's not the case, feel free to re-open this and let us know, as you've found a bug.

**Comment by pavittarx** [comment]
Well, Thanks, that was an error with Javascript, it is working via Javascript but not when I pass the parameter via CSS. If I change color property using CSS classes, it doesn't change. 
If you check my JS I have binded the 'complete' state of UI elements to 'stripe_complete' class, now 

```css
.stripe_form_container input:valid,.stripe_complete{
    color:#00e676;
    box-shadow: 0 0.2rem 0.1rem -0.1rem #00e676;
}
```
This is the snippet of my CSS, also available in the code at the top.The box-shadow property works, but the color property is ineffective. Here, is the snippet of my console you asked for. :)
![image](https://user-images.githubusercontent.com/29155477/38713866-2a2d18f8-3ef1-11e8-88ac-8107245f725d.png)

**Comment by jez** [comment]
Because of the way Stripe.js works, setting any of style properties you see in [this list][1] must be specified in JavaScript (specifying them in CSS will not work). Notice that `box-shadow` is not one of the properties in that list, which is why it works in CSS.

Since you mention that it's working when you set `color` via JavaScript, I'm going to close this issue. The issues in this repo are specifically for bugs in the Elements examples contained within this repo.


[1]: https://stripe.com/docs/stripe-js/reference#element-options


If you're having general trouble with Stripe.js or your Stripe integration, please reach out to us using the form at https://support.stripe.com/email or come chat with us at #stripe on freenode. We're very proud of our level of service, and we're more than happy to help you out with your integration.

Thanks!

**Comment by pavittarx** [comment]
I guess, you are not understanding my reference clearly, Please let me state it more clearly.
I have binded these [base, invalid, complete] states/list of stripe elements using JS to CSS classes that I am using to change styles.
```javascript
 let classes = {
    base: 'stripe_base',
    empty: 'stripe_empty',
    focus: 'stripe_focus',
    invalid: 'stripe_invalid',
    complete: 'stripe_complete'
}
/* Binds the classes to Card Number Stripe Element*/
let cardNumber = elements.create('cardNumber', { classes: classes, style:style});
```

Now if you check my CSS 
```css
.stripe_form_container input:invalid,.stripe_invalid {
    color:#ff0000; /* This color property works very well, I don't have to pass it using style object in JS. */
    box-shadow: 0 0.2rem 0.1rem -0.1rem #ff0000ff;
}

.stripe_form_container input:valid,.stripe_complete{
    color:#00e676; /* This doesn't when passed with CSS, I have to assign it using style object in JS */
    box-shadow: 0 0.2rem 0.1rem -0.1rem #00e676;
}
```

So I have to use it as a workaround by defining a style in Javascript & then pass it as a parameter, thats not my first intention to do, but I have to do it since, the other way doesn't work. 
The reason I want to do it in CSS. just to keep my styling code & JS code separate, from each other as much as possible.
I assume it is a bug, since the class .stripe_invalid is accepting the color changes & .stripe_complete is not.
