### ISSUE TITLE
data-amount

### ISSUE THREAD

**Issue by mohitgarg** [stripe/elements-examples#48]
Where can I specify the data-amount to be charged? Couldn't find anything in the documentation as well

**Comment by pavittarx** [comment]
The amount is charged using a charge object, you can check the documentation here -  https://stripe.com/docs/charges 
Also, you must first tokenize the card information before proceeding to make charges,If you are not sure how to tokenize the data, use this part of the docs 
https://stripe.com/docs/stripe-js
Also, have a look at [Reference Section](https://stripe.com/docs/stripe-js/reference) of StripeJs Elements for a better undestanding. 
I hope everything is covered, the issue may be closed soon.

**Comment by cweiss-stripe** [comment]
Thank you @pavittarx for explaining this and linking to the relevant sections of the documentation.  👍 

@mohitgarg if you still have questions about your Stripe integration that can't be answered by reading the docs that @pavittarx linked to, please reach out to us using the form at https://support.stripe.com/email or come chat with us at #stripe on freenode.
