### ISSUE TITLE
Tons of errors while looking in inspector

### ISSUE THREAD

**Issue by mokumax** [stripe/elements-examples#56]
![stripe-element](https://user-images.githubusercontent.com/1252584/41731576-bd351d76-754c-11e8-8d96-8691f01c43ca.PNG)

I have AdBlock extension in Chrome but I have this website (which is localhost) whitelisted.

**Comment by asolove-stripe** [comment]
Hi @mokumax, thanks for reporting this. We have heard reports that in some versions of AdBlock, there is a bug where these messages appear on pages involving iframes and Content Security Policies, which stripe.js requires. Unfortunately it seems to be an issue on their side and we are waiting for a fix.
